# Crystal Representations

<div style="background-color: #f8d7da; border-left: 6px solid #ccc; margin: 20px; padding: 15px;">
    <strong>💡 John Stewart Bell:</strong> Theoretical physicists live in a classical world, looking out into a quantum-mechanical world.
</div>

<iframe class="speakerdeck-iframe" frameborder="0" src="https://speakerdeck.com/player/431daa62140b472bb2b19c499ebb73f5" title="Machine Learning for Materials (Lecture 4)" allowfullscreen="true" style="border: 0px; background-clip: padding-box; background-color: rgba(0, 0, 0, 0.1); margin: 0px; padding: 0px; border-radius: 6px; box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 40px; width: 50%; height: auto; aspect-ratio: 560 / 420;" data-ratio="1.3333333333333333"></iframe>

[Lecture slides](https://speakerdeck.com/aronwalsh/mlformaterials-lecture4-data)

## 🚀 Navigating crystal space

Our world can be described as a three-dimensional space (or a four-dimensional spacetime continuum). Chemical space is even more vast when you think of all of the compositions and structures that can be built from combinations of the 118 known elements in the Periodic Table! Considering only carbon atoms, C-C bonds can be used to form molecules, rods, spheres, sheets, and extended crystals.

Today's goal is to explore the combinatorial explosion that occurs for multi-component solids using informatics tools. You will learn:

- How to construct and visualise a crystal structure using *pymatgen*
- How to featurise structures using *dscribe*
- How to generate and explore charge-balanced compositions using *smact*

In [1]:
# Installation of libraries
!pip install matminer --quiet
!pip install smact==3.2.0 --quiet
!pip install plotly --quiet
!pip install multiprocess --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 74.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.9/51.9 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 85.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 73.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 23.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 24.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 962.5/962.5 kB 53.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 78.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.

In [2]:
# Import of modules
import pandas as pd  # Data manipulation with DataFrames
import numpy as np  # Numerical operations
import matplotlib.pyplot as plt  # Plotting
import plotly.express as px  # More plotting
import pprint  # Pretty print data structures

<details>
<summary>Colab error solution</summary>
If running the import module cell fails with an "AttributeError", click `Runtime` -> `Restart Session` and then simply rerun the cell.
</details>

## ABX<sub>3</sub> perovskite structure

Let's start by considering how we can represent a crystal structure in Python. We will make use of the functionality for storing and representing crystal structures in `pymatgen`.

The [`Structure` module](https://pymatgen.org/pymatgen.core.structure.html) contains the `Structure` class which can be used to represent the unit cell of a crystal.  Remember, this is the simplest repeat unit of a crystal that is defined by three unit cell lengths (**a**,**b**,**c**), three angles ($\alpha,\beta,\gamma$), and the fractional coordinates of the atoms that it contains.

Below, we will create a model of a cubic perovskite from its spacegroup, Pm3̅m (No. 221). For a cubic unit cell **a** = **b** = **c** and $\alpha = \beta = \gamma = 90 ^{\circ}$, so we only need to define the length of **a**.

We will now create a structure for CsPbI<sub>3</sub> from a spacegroup using the class method `Structure.from_spacegroup()`. This requires the space group, lattice parameters, atom types, and coordinates.

![image](https://github.com/aronwalsh/MLforMaterials/blob/2026/images/2_CsPbI3.png?raw=1)

This graphic was created using [VESTA](https://jp-minerals.org/vesta/en).

In [3]:
# Create a structure object for cubic CsPbI3 using pymatgen
from pymatgen.core import Structure, Lattice  # Structure modules

CsPbI3 = Structure.from_spacegroup(
'Pm-3m', # Spacegroup for a cubic perovskite
Lattice.cubic(6.41), # Cubic spacing of 6.41 Å
['Pb2+', 'Cs+', 'I-'], # Unique species of the ABX3 compound
[[0.,0.,0.],[0.5,0.5,0.5],[0.,0.,0.5]] # Fractional atomic coordinates of each site
)

# Print the structure details
print(CsPbI3)

Full Formula (Cs1 Pb1 I3)
Reduced Formula: CsPbI3
abc   :   6.410000   6.410000   6.410000
angles:  90.000000  90.000000  90.000000
pbc   :       True       True       True
Sites (5)
  #  SP      a    b    c
---  ----  ---  ---  ---
  0  Pb2+  0    0    0
  1  Cs+   0.5  0.5  0.5
  2  I-    0    0.5  0
  3  I-    0.5  0    0
  4  I-    0    0    0.5


Note that it has used the symmetry from the space group information to create a primitive unit cell with 5 atoms. Within `pymatgen`, we can export crystal structures to a variety of file formats using the `to` method of the `Structure` class. Some of these include the Crystallographic Information Format (cif) and POSCAR (the standard file format for the density functional theory code [VASP](https://www.vasp.at/wiki/index.php/Category:Theory)). A complete list of file formats can be found in [the docs](https://pymatgen.org/pymatgen.core.structure.html#pymatgen.core.structure.IStructure.to) for the `Structure` class.

Note, the `filename` argument of the `to` method needs to be specified to save the file to disk. Only supplying the `fmt` argument will result in a string being returned.

In [4]:
# Print the file to screen
print('\nThe CIF format for CsPbI3 is shown below:\n')
print(CsPbI3.to(fmt='cif'))

# Export the structure to a CIF
# CsPbI3.to(filename='CsPbI3.cif')

# Download the CIF from Google Colab
# from google.colab import files
# files.download('CsPbI3.cif')


The CIF format for CsPbI3 is shown below:

# generated using pymatgen
data_CsPbI3
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   6.41000000
_cell_length_b   6.41000000
_cell_length_c   6.41000000
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   CsPbI3
_chemical_formula_sum   'Cs1 Pb1 I3'
_cell_volume   263.37472100
_cell_formula_units_Z   1
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_type_symbol
 _atom_type_oxidation_number
  Cs+  1.0
  Pb2+  2.0
  I-  -1.0
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Pb2+  Pb0  1  0.00000000  0.00000000  0.00000000  1
  Cs+  Cs1  1  0.50000000  0.50000000  0.50000000  1
  I-  I2  1  0.00000000  0.50000000  0.00000000  1
  I-  I3  1  0.50000000  0.00000000  0.00000000  1

<details>
<summary> Code hint </summary>
You can export a .cif by uncommenting and running the lines above. These files can be opened in a visualiser of your choice (e.g. VESTA or Crystalmaker).
</details>

There are many useful functions for analysing these structures. As we are using Python, this analysis can be extended to large databases of thousands to millions of entries. Below we check distances and two methods for assigning coordination numbers (detailed [here](https://pubs.acs.org/doi/10.1021/acs.inorgchem.0c02996)).

In [6]:
# Distance between the first and second atoms
distance = CsPbI3.get_distance(0, 1)
print(f"Distance between Pb and Cs: {distance:.2f} Å")

# Coordination environment of Pb using Voronoi tessellation
from pymatgen.analysis.local_env import VoronoiNN
vnn = VoronoiNN()
coord_env = vnn.get_nn(CsPbI3, 0)
print(f"\nCoordination number of Pb (VoronoiNN): {len(coord_env)}")

# Coordination environment of Pb using Crystal Near-Neighbor Algorithm
from pymatgen.analysis.local_env import CrystalNN
crystal_nn = CrystalNN()
coord_env_crystal = crystal_nn.get_nn(CsPbI3, 0)
print(f"\nCoordination number of Pb (CrystalNN): {len(coord_env_crystal)}\n")
for site in coord_env_crystal:
    print(f"Distance to {site.species_string}: {CsPbI3.get_distance(0, site.index):.2f} Å")

# Assign oxidation states
from pymatgen.analysis.bond_valence import BVAnalyzer
analyzer = BVAnalyzer()
valences = analyzer.get_valences(CsPbI3)
print(f"\nAssigned oxidation states:")
for site, valence in zip(CsPbI3.sites, valences):
    print(f"{site.species_string}: {valence:+.1f}")

Distance between Pb and Cs: 5.55 Å

Coordination number of Pb (VoronoiNN): 6

Coordination number of Pb (CrystalNN): 6

Distance to I-: 3.21 Å
Distance to I-: 3.21 Å
Distance to I-: 3.21 Å
Distance to I-: 3.21 Å
Distance to I-: 3.21 Å
Distance to I-: 3.21 Å

Assigned oxidation states:
Pb2+: +2.0
Cs+: +1.0
I-: -1.0
I-: -1.0
I-: -1.0


You can imagine how to hand-build simple feature vectors to describe crystal strutures, but we can do this more systematically using purpose-built representations for machine learning. Let's try to construct a Sine Coulomb matrix that encodes atomic distances with `matminer`.

In [9]:
from matminer.featurizers.structure import SineCoulombMatrix

# Sine matrix representation
scm = SineCoulombMatrix(flatten=False)
scm.fit([CsPbI3])
scm_fea = scm.featurize(CsPbI3)
np.set_printoptions(precision=2, suppress=True)
print("\nSine Coulomb matrix features:\n", np.array(scm_fea))


Sine Coulomb matrix features:
 [[[19594.01   214.96   358.78   358.78   358.78]
  [  214.96  7513.47   170.16   170.16   170.16]
  [  358.78   170.16  6874.36   163.97   163.97]
  [  358.78   170.16   163.97  6874.36   163.97]
  [  358.78   170.16   163.97   163.97  6874.36]]]


The output is a 5x5 matrix because there are 5 atoms in the unit cell of CsPbI<sub>3</sub>. Each element M<sub>ij</sub> in the matrix represents the interaction between atoms i and j.

- The **diagonal elements** (i.e., M<sub>ii</sub>) represent the interaction of each atom with itself, which depends on the atomic number Z<sub>i</sub> and is calculated as 0.5Z<sub>i</sub><sup>2.4</sup>.
- The **off-diagonal elements** (i.e., M<sub>ij</sub> for i ≠ j) are inspired by the Coulomb interaction between different atoms i and j, scaled by their atomic numbers Z<sub>i</sub> and Z<sub>j</sub>, and the distance between them in the periodic structure.

This matrix encodes information from both the positions and types of atoms, providing a feature vector. Let's see what happens when the chemistry changes.

In [14]:
from pymatgen.core import Species
from matminer.featurizers.structure import SineCoulombMatrix

# Re-compute scm_fea to ensure it's defined
scm = SineCoulombMatrix(flatten=False)
scm.fit([CsPbI3])
scm_fea = scm.featurize(CsPbI3)

# Substitute Pb with Sn
CsSnI3 = CsPbI3.copy()
CsSnI3.replace_species({Species("Pb2+"): Species("Sn2+")})

# Sine matrix representation for CsSnI3
scm = SineCoulombMatrix(flatten=False)
scm.fit([CsSnI3])
scm_fea_sn = scm.featurize(CsSnI3)

np.set_printoptions(precision=2, suppress=True)
print("\nOriginal Coulomb matrix features:\n", np.array(scm_fea))
print("\nSine Coulomb matrix features with Sn replacing Pb:\n", np.array(scm_fea_sn))


Original Coulomb matrix features:
 [[[19594.01   214.96   358.78   358.78   358.78]
  [  214.96  7513.47   170.16   170.16   170.16]
  [  358.78   170.16  6874.36   163.97   163.97]
  [  358.78   170.16   163.97  6874.36   163.97]
  [  358.78   170.16   163.97   163.97  6874.36]]]

Sine Coulomb matrix features with Sn replacing Pb:
 [[[5977.2   131.07  218.77  218.77  218.77]
  [ 131.07 7513.47  170.16  170.16  170.16]
  [ 218.77  170.16 6874.36  163.97  163.97]
  [ 218.77  170.16  163.97 6874.36  163.97]
  [ 218.77  170.16  163.97  163.97 6874.36]]]


<div style="background-color: #d4edda; border-left: 6px solid #ccc; margin: 20px; padding: 15px; border-radius: 5px;">
    <strong>🐢 Take a beat:</strong> Think about why some values remain the same, others are different, and where they are placed in the matrix.
</div>

While useful, this is not the state-of-the-art approach. One reason is that only pairwise information is included, e.g. two structures with different angles between the component atoms may have the same numerical representation. The [DScribe tutorials](https://singroup.github.io/dscribe/latest/tutorials/tutorials.html) contain a description of more advanced representations such as Smooth Overlap of Atomic Positions (SOAP) that includes both 2-body and 3-body descriptors of structure.

## Possible Perovskites

We can make an ionic approximation for CsPbI<sub>3</sub> and consider that the crystal is formed of Cs<sup>+</sup>, Pb<sup>2+</sup>, and I<sup>-</sup> ions. The crystal is charge neutral overall as the sum of cations (3<sup>+</sup>) is balanced by the sum of anions (3<sup>-</sup>). This charge balance is also what the structural analysis we performed suggested. It is worth remembering that bonding in real solids is more complicated than a simple classification of "ionic", "covalent" or "metallic" (e.g. see this [perspective](https://www.nature.com/articles/s41563-018-0165-7)).

Let's now screen a large space of possible Cs-Pb-I compounds by making use of our materials informatics code [smact](https://github.com/WMD-group/SMACT). We will navigate this combinatorial chemical space by applying charge balance filters to possible ABX₃ compounds.

In [12]:
import smact
from smact.screening import smact_filter
import pprint

# Define a list of three elements to screen for A-B-X compounds
elements = ["Cs", "Pb"]

# Convert element symbols into smact.Element objects
element_objects = [smact.Element(e) for e in elements]

# Apply smact_filter to find valid compositions within a stoichiometry threshold
allowed_combinations = smact_filter(element_objects, threshold=8)

# Display the allowed combinations in a readable format
print(f"Number of allowed combinations: --> {len(allowed_combinations)} <--")
pprint.pprint("(elements), (charges), (stoichiometry)")
pprint.pprint(allowed_combinations)

Number of allowed combinations: --> 2 <--
'(elements), (charges), (stoichiometry)'
[(('Cs', 'Pb'), (1, -4), (4, 1)), (('Cs', 'Pb'), (1, -1), (1, 1))]


<details>
<summary> Code hint </summary>
Close all quotations and add "I" to the elements list.
</details>

That set includes many possibilities including the regular perovskite stoichiometry CsPbI<sub>3</sub>, which has a 1:1:3 ratio, as well as many others such as Cs<sub>2</sub>Pb<sub></sub>I<sub>4</sub>, which forms a layered (2D octahedral connectivity) perovskite.  Some of the entries have Pb in a 4- charge state (known as the plumbide anion).

Before the exploration of metal halides, metals oxides were the most commonly studied perovskites. Let's explore how about A-B-O compounds can be formed.

In [15]:
import itertools
import multiprocess as mp # Using multiprocess instead of multiprocessing
from smact import Element, element_dictionary, ordered_elements
from smact.screening import smact_filter

# Load all elements and then limit to Bi
all_elements = element_dictionary()
elements = [all_elements[symbol] for symbol in ordered_elements(1, 83)]

# Generate all AB combinations + add oxygen (O)
O = Element("O") # Define Oxygen element once
metal_pairs = itertools.combinations(elements, 2)
ternary_systems = [[*pair, O] for pair in metal_pairs]
print(f"Raw element combinations (ABO): --> {len(ternary_systems)} <--")

def safe_smact_filter(system):
    """Avoid TypeErrors from smact_filter in multiprocessing."""
    try:
        return smact_filter(system)
    except TypeError:
        return []

# Apply chemical filters using multiprocessing
# The __name__ == "__main__" block is essential for multiprocessing in some environments
# but often causes issues in interactive environments like Colab when wrapped incorrectly.
# The fix uses pool.map with a safe wrapper.
with mp.Pool(processes=4) as pool:
    result = pool.map(safe_smact_filter, ternary_systems)

# Flatten the list
flat_list = [composition for sublist in result if sublist for composition in sublist]
print(f"Allowed stoichiometries: --> {len(flat_list)} <--")

# Print some valid compositions
print("  elements, oxidation states, stoichiometries")
for entry in flat_list[-10:]:
    print(entry)

Raw element combinations (ABO): --> 3403 <--
Allowed stoichiometries: --> 652170 <--
  elements, oxidation states, stoichiometries
(('Pb', 'Bi', 'O'), (4, 3, -2), (1, 4, 8))
(('Pb', 'Bi', 'O'), (4, 3, -2), (2, 2, 7))
(('Pb', 'Bi', 'O'), (4, 3, -1), (1, 1, 7))
(('Pb', 'Bi', 'O'), (4, 4, -2), (1, 1, 4))
(('Pb', 'Bi', 'O'), (4, 4, -2), (1, 2, 6))
(('Pb', 'Bi', 'O'), (4, 4, -2), (1, 3, 8))
(('Pb', 'Bi', 'O'), (4, 4, -2), (2, 1, 6))
(('Pb', 'Bi', 'O'), (4, 4, -2), (3, 1, 8))
(('Pb', 'Bi', 'O'), (4, 4, -1), (1, 1, 8))
(('Pb', 'Bi', 'O'), (4, 5, -2), (1, 2, 7))


In [ ]:
import itertools
import multiprocess as mp
from smact import Element, element_dictionary, ordered_elements
from smact.screening import smact_filter

all_elements = element_dictionary()
elements = [all_elements[symbol] for symbol in ordered_elements(1, 83)]

O = Element("O")
ternary_systems = [[a, b, O] for a, b in itertools.combinations(elements, 2)]
print(f"Raw element combinations (ABO): --> {len(ternary_systems)} <--")

def safe_smact_filter(system):
    """Avoid TypeErrors from smact_filter in multiprocessing."""
    try:
        return smact_filter(system)
    except TypeError:
        return []

with mp.Pool(processes=4) as pool:
    result = pool.map(safe_smact_filter, ternary_systems)

flat_list = [comp for sub in result if sub for comp in sub]
print(f"Allowed stoichiometries: --> {len(flat_list)} <--")

That's a lot of potential compounds. Let's filter them down to just keep ABO<sub>3</sub>.

In [16]:
# Filter for (1,1,3) stoichiometries with oxide anion
filtered_compositions = [
    comp for comp in flat_list
    if comp[2] == (1, 1, 3)
    and 'O' in comp[0]
    and comp[1][comp[0].index('O')] == -2  # Oxide
    and comp[1][0] > 0  # First element must have a positive charge
    and comp[1][1] > 0  # Second element must have a positive charge
]

print(f"Filtered (1,1,3) stoichiometries with O(-2): --> {len(filtered_compositions)} <--")

# Print a few filtered compositions
print("  elements, oxidation states, stoichiometries")
for entry in filtered_compositions[-10:]:
    print(entry)

Filtered (1,1,3) stoichiometries with O(-2): --> 6019 <--
  elements, oxidation states, stoichiometries
(('Hg', 'Bi', 'O'), (1, 5, -2), (1, 1, 3))
(('Hg', 'Bi', 'O'), (2, 4, -2), (1, 1, 3))
(('Tl', 'Pb', 'O'), (2, 4, -2), (1, 1, 3))
(('Tl', 'Pb', 'O'), (3, 3, -2), (1, 1, 3))
(('Tl', 'Bi', 'O'), (1, 5, -2), (1, 1, 3))
(('Tl', 'Bi', 'O'), (2, 4, -2), (1, 1, 3))
(('Tl', 'Bi', 'O'), (3, 3, -2), (1, 1, 3))
(('Pb', 'Bi', 'O'), (2, 4, -2), (1, 1, 3))
(('Pb', 'Bi', 'O'), (3, 3, -2), (1, 1, 3))
(('Pb', 'Bi', 'O'), (4, 2, -2), (1, 1, 3))


That's still too many to scroll through, but we can make a plot to visualise the combinations.

In [22]:
# List of elements to include
elements = sorted(set([el for comp in filtered_compositions for el in comp[0]]))

# DataFrame to hold the allowed combinations
matrix = pd.DataFrame(0, index=elements, columns=elements)

# Fill the matrix with allowed combinations
for comp in filtered_compositions:
    A, B, O = comp[0]
    matrix.at[A, B] = 1
    matrix.at[B, A] = 1

# Create the plot
fig = px.imshow(
    matrix.values,
    labels=dict(x="Element A", y="Element B", color="Allowed"),
    x=matrix.columns,
    y=matrix.index,
    color_continuous_scale="Plasma",
)

# Update layout for smaller font size
fig.update_layout(
    xaxis=dict(tickfont=dict(size=10)),
    yaxis=dict(tickfont=dict(size=10)),
    title="Charge allowed ABO<sub>3</sub> combinations",
    title_x=0.5,
)

fig.show()

## 🚨 Exercise 4

<div style="background-color: #dceefb; border-left: 6px solid #ccc; margin: 20px; padding: 15px; border-radius: 5px;">
    <strong>💡 Coding exercises:</strong> The exercises are designed to apply what you have learned with room for creativity. It is fine to discuss solutions with your classmates, but the actual code should not be directly copied.
</div>

### Your details

In [18]:
import numpy as np

# Insert your values
Name = "Hanzhi Zhu" # Replace with your name
CID = 2243276 # Replace with your College ID (as a numeric value with no leading 0s)

# Set a random seed using the CID value
CID = int(CID)
np.random.seed(CID)

# Print the message
print("This is the work of " + Name + " [CID: " + str(CID) + "]")

This is the work of Hanzhi Zhu [CID: 2243276]


### 🧪 Problem: Exploring the Chemical Space of Nitrides

Materials informatics allows us to systematically explore the combinatorial space of chemical composition and structural constraints. In this exercise, we will screen for valid novel perovskites using charge balance rules, and compare them to known perovskites.

Tasks will be introduced in class.

In [19]:
# Task 1: Generate Nitride Perovskite Candidates (ABN3)

!pip install smact==3.2.0 --quiet
!pip install multiprocess --quiet

import itertools
import multiprocess as mp
from smact import Element, element_dictionary, ordered_elements
from smact.screening import smact_filter

# Load elements (same range as slides: Z=1..83)
all_elements = element_dictionary()
elements = [all_elements[symbol] for symbol in ordered_elements(1, 83)]

# Fix anion as nitride
N = Element("N")

# Generate all AB pairs + N -> ternary systems [A, B, N]
ternary_systems = [[a, b, N] for a, b in itertools.combinations(elements, 2)]
print(f"Raw element combinations (ABN): --> {len(ternary_systems)} <--")

def safe_smact_filter(system):
    """Avoid TypeErrors from smact_filter in multiprocessing."""
    try:
        return smact_filter(system)
    except TypeError:
        return []

# Apply smact_filter with multiprocessing (same pattern as slides)
with mp.Pool(processes=4) as pool:
    result = pool.map(safe_smact_filter, ternary_systems)

# Flatten results
flat_list = [comp for sub in result if sub for comp in sub]
print(f"Allowed stoichiometries (all): --> {len(flat_list)} <--")

# Filter for ABN3 with N(-3), A>0, B>0
filtered_nitrides = [
    comp for comp in flat_list
    if comp[2] == (1, 1, 3)                      # stoichiometry (1,1,3)
    and "N" in comp[0]                           # contains N
    and comp[1][comp[0].index("N")] == -3        # nitride anion
    and comp[1][0] > 0                           # A is cation
    and comp[1][1] > 0                           # B is cation
]

print(f"Total valid nitride compositions ABN3 with N(-3): --> {len(filtered_nitrides)} <--")

# (Optional) print a few examples
print(" elements, oxidation states, stoichiometries")
for entry in filtered_nitrides[-10:]:
    print(entry)



Raw element combinations (ABN): --> 3403 <--
Allowed stoichiometries (all): --> 1681422 <--
Total valid nitride compositions ABN3 with N(-3): --> 2426 <--
 elements, oxidation states, stoichiometries
(('Ir', 'Bi', 'N'), (4, 5, -3), (1, 1, 3))
(('Ir', 'Bi', 'N'), (5, 4, -3), (1, 1, 3))
(('Ir', 'Bi', 'N'), (6, 3, -3), (1, 1, 3))
(('Pt', 'Au', 'N'), (4, 5, -3), (1, 1, 3))
(('Pt', 'Pb', 'N'), (5, 4, -3), (1, 1, 3))
(('Pt', 'Bi', 'N'), (4, 5, -3), (1, 1, 3))
(('Pt', 'Bi', 'N'), (5, 4, -3), (1, 1, 3))
(('Au', 'Pb', 'N'), (5, 4, -3), (1, 1, 3))
(('Au', 'Bi', 'N'), (5, 4, -3), (1, 1, 3))
(('Pb', 'Bi', 'N'), (4, 5, -3), (1, 1, 3))


In [27]:
# Task 2
import pandas as pd
import plotly.express as px

# List of elements to include
elements = sorted(set([el for comp in filtered_nitrides for el in comp[0]]))

# DataFrame to hold the allowed combinations
matrix = pd.DataFrame(0, index=elements, columns=elements)

# Fill the matrix with allowed combinations
for comp in filtered_nitrides:
    A, B, N = comp[0]
    matrix.at[A, B] = 1
    matrix.at[B, A] = 1

# Create the plot
fig = px.imshow(
    matrix.values,
    labels=dict(x="Element A", y="Element B", color="Allowed"),
    x=matrix.columns,
    y=matrix.index,
    color_continuous_scale="Plasma",
)

# Update layout
fig.update_layout(
    xaxis=dict(tickfont=dict(size=10)),
    yaxis=dict(tickfont=dict(size=10)),
    title="Charge allowed ABN<sub>3</sub> combinations",
    title_x=0.5,
)

fig.show()

print("The A–B matrix visualisation highlights the discrete chemical space of charge-balanced nitride perovskites, revealing a more restricted set of allowed combinations compared with oxides due to the higher anion charge of N³⁻.")


The A–B matrix visualisation highlights the discrete chemical space of charge-balanced nitride perovskites, revealing a more restricted set of allowed combinations compared with oxides due to the higher anion charge of N³⁻.


In [25]:
# Optional Task 3: Check predicted ABN3 against Materials Project

import random
import pandas as pd
from mp_api.client import MPRester

# 1) SET YOUR MP API KEY

MP_API_KEY = "jQeflRrmelyQ3G8n21fg5GsyV2l43vYD"

# 2) helper: ABN3 entry -> formula

def entry_to_formula(entry):
    elems = entry[0]      # ["Ba","Ti","N"]
    stoich = entry[2]     # (1,1,3)
    formula = ""
    for el, n in zip(elems, stoich):
        if n == 1:
            formula += el
        else:
            formula += f"{el}{n}"
    return formula

# 3) prepare predicted formula

pred_formulas = [entry_to_formula(e) for e in filtered_nitrides]
pred_formulas = sorted(set(pred_formulas))

print("Total predicted ABN3 formulas:", len(pred_formulas))
print("Example:", pred_formulas[:10])

# 4) randomly sample for querying


N_QUERY = 50
random.seed(0)

query_list = random.sample(pred_formulas,
                           k=min(N_QUERY, len(pred_formulas)))

# 5) query Materials Project

rows = []

with MPRester(MP_API_KEY) as mpr:

    for formula in query_list:

        try:
            results = mpr.materials.summary.search(
                formula=formula,
                fields=[
                    "material_id",
                    "formula_pretty",
                    "energy_above_hull",
                    "formation_energy_per_atom",
                    "theoretical"
                ]
            )

            if len(results) > 0:

                # choose lowest energy_above_hull entry
                best = sorted(
                    results,
                    key=lambda x: 1e9 if x.energy_above_hull is None else x.energy_above_hull
                )[0]

                rows.append({
                    "query_formula": formula,
                    "found_on_MP": True,
                    "mp_id": best.material_id,
                    "mp_formula": best.formula_pretty,
                    "energy_above_hull (eV/atom)": best.energy_above_hull,
                    "formation_energy (eV/atom)": best.formation_energy_per_atom,
                    "theoretical": best.theoretical,
                    "num_entries": len(results)
                })

            else:
                rows.append({
                    "query_formula": formula,
                    "found_on_MP": False,
                    "mp_id": None,
                    "mp_formula": None,
                    "energy_above_hull (eV/atom)": None,
                    "formation_energy (eV/atom)": None,
                    "theoretical": None,
                    "num_entries": 0
                })

        except Exception as e:
            print("Error querying:", formula, e)

# 6) results table

df_mp = pd.DataFrame(rows)
df_mp = df_mp.sort_values(
    by=["found_on_MP", "energy_above_hull (eV/atom)"],
    ascending=[False, True],
    na_position="last"
)

print(df_mp.head(20))



# 7) quick summary (for report)

n_found = (df_mp["found_on_MP"] == True).sum()

print("\nSummary:")
print("Found on Materials Project:", n_found, "/", len(df_mp))

if n_found > 0:
    print("Lowest energy above hull:",
          df_mp[df_mp["found_on_MP"] == True]["energy_above_hull (eV/atom)"].min())


Total predicted ABN3 formulas: 1200
Example: ['AgIN3', 'AgIrN3', 'AgOsN3', 'AgReN3', 'AgTeN3', 'AgWN3', 'AgXeN3', 'AlCrN3', 'AlFeN3', 'AlIrN3']


Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/5 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

   query_formula  found_on_MP       mp_id mp_formula  \
3         MoLaN3         True   mp-989631     LaMoN3   
47         YTcN3         True   mp-989640      YTcN3   
11        LaTaN3         True   mp-989620     LaTaN3   
1          ScWN3         True  mp-1246967      ScWN3   
18         VMoN3         True  mp-1246912      VMoN3   
0          SInN3        False        None       None   
2         BeRuN3        False        None       None   
4         TiCrN3        False        None       None   
5         TcLuN3        False        None       None   
6         SbErN3        False        None       None   
7         OsBiN3        False        None       None   
8         TbTaN3        False        None       None   
9         RuAuN3        False        None       None   
10        ZrSbN3        False        None       None   
12        TePtN3        False        None       None   
13        FeBiN3        False        None       None   
14        NbReN3        False        None       

In [29]:
print("From 50 sampled ABN₃ candidates, 5 were found on Materials Project. One compound (LaMoN₃) is predicted to be thermodynamically stable (E_hull= 0 eV/atom), while others are metastable. Most predicted compositions are not reported, suggesting that nitride perovskites are underexplored and that charge-balance screening alone does not ensure stability.")

From 50 sampled ABN₃ candidates, 5 were found on Materials Project. One compound (LaMoN₃) is predicted to be thermodynamically stable (E_hull= 0 eV/atom), while others are metastable. Most predicted compositions are not reported, suggesting that nitride perovskites are underexplored and that charge-balance screening alone does not ensure stability.


<div style="background-color: #d4edda; border-left: 6px solid #ccc; margin: 20px; padding: 15px; border-radius: 5px;">
    <strong>📓 Submission:</strong> When your notebook is complete in Google Colab, go to <em>File > Download</em> and choose <code>.ipynb</code>. The completed file should be uploaded to Blackboard under assignments for MATE70026.
</div>

## 🌊 Dive deeper

* _Level 1:_ Tackle Chapter 8 on Linear Unsupervised Learning in [Machine Learning Refined](https://github.com/jermwatt/machine_learning_refined#what-is-new-in-the-second-edition).

* _Level 2:_ Read about our attempt to screen _all inorganic materials_ (with caveats) in the journal [Chem](https://doi.org/10.1016/j.chempr.2016.09.010).

* _Level 3:_ Watch a [seminar](https://www.youtube.com/watch?v=gd-uahI5xbA) by quantum chemist Anatole von Lilienfeld on chemical space.